package com.tony.demo.message.model;

import java.io.Serializable;

public class WechatMessageReplyStatus implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.component_appid
     *
     * @mbg.generated
     */
    private String componentAppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.authorizer_appid
     *
     * @mbg.generated
     */
    private String authorizerAppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.message_type
     *
     * @mbg.generated
     */
    private Byte messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.message_open
     *
     * @mbg.generated
     */
    private Byte messageOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.created_time
     *
     * @mbg.generated
     */
    private Long createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_message_reply_status.updated_time
     *
     * @mbg.generated
     */
    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.id
     *
     * @return the value of wechat_message_reply_status.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.id
     *
     * @param id the value for wechat_message_reply_status.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.group_id
     *
     * @return the value of wechat_message_reply_status.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.group_id
     *
     * @param groupId the value for wechat_message_reply_status.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.component_appid
     *
     * @return the value of wechat_message_reply_status.component_appid
     *
     * @mbg.generated
     */
    public String getComponentAppid() {
        return componentAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.component_appid
     *
     * @param componentAppid the value for wechat_message_reply_status.component_appid
     *
     * @mbg.generated
     */
    public void setComponentAppid(String componentAppid) {
        this.componentAppid = componentAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.authorizer_appid
     *
     * @return the value of wechat_message_reply_status.authorizer_appid
     *
     * @mbg.generated
     */
    public String getAuthorizerAppid() {
        return authorizerAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.authorizer_appid
     *
     * @param authorizerAppid the value for wechat_message_reply_status.authorizer_appid
     *
     * @mbg.generated
     */
    public void setAuthorizerAppid(String authorizerAppid) {
        this.authorizerAppid = authorizerAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.user_name
     *
     * @return the value of wechat_message_reply_status.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.user_name
     *
     * @param userName the value for wechat_message_reply_status.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.message_type
     *
     * @return the value of wechat_message_reply_status.message_type
     *
     * @mbg.generated
     */
    public Byte getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.message_type
     *
     * @param messageType the value for wechat_message_reply_status.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(Byte messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.message_open
     *
     * @return the value of wechat_message_reply_status.message_open
     *
     * @mbg.generated
     */
    public Byte getMessageOpen() {
        return messageOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.message_open
     *
     * @param messageOpen the value for wechat_message_reply_status.message_open
     *
     * @mbg.generated
     */
    public void setMessageOpen(Byte messageOpen) {
        this.messageOpen = messageOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.deleted
     *
     * @return the value of wechat_message_reply_status.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.deleted
     *
     * @param deleted the value for wechat_message_reply_status.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.created_time
     *
     * @return the value of wechat_message_reply_status.created_time
     *
     * @mbg.generated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.created_time
     *
     * @param createdTime the value for wechat_message_reply_status.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_message_reply_status.updated_time
     *
     * @return the value of wechat_message_reply_status.updated_time
     *
     * @mbg.generated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_message_reply_status.updated_time
     *
     * @param updatedTime the value for wechat_message_reply_status.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WechatMessageReplyStatus other = (WechatMessageReplyStatus) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getComponentAppid() == null ? other.getComponentAppid() == null : this.getComponentAppid().equals(other.getComponentAppid()))
            && (this.getAuthorizerAppid() == null ? other.getAuthorizerAppid() == null : this.getAuthorizerAppid().equals(other.getAuthorizerAppid()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getMessageType() == null ? other.getMessageType() == null : this.getMessageType().equals(other.getMessageType()))
            && (this.getMessageOpen() == null ? other.getMessageOpen() == null : this.getMessageOpen().equals(other.getMessageOpen()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getComponentAppid() == null) ? 0 : getComponentAppid().hashCode());
        result = prime * result + ((getAuthorizerAppid() == null) ? 0 : getAuthorizerAppid().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getMessageType() == null) ? 0 : getMessageType().hashCode());
        result = prime * result + ((getMessageOpen() == null) ? 0 : getMessageOpen().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", componentAppid=").append(componentAppid);
        sb.append(", authorizerAppid=").append(authorizerAppid);
        sb.append(", userName=").append(userName);
        sb.append(", messageType=").append(messageType);
        sb.append(", messageOpen=").append(messageOpen);
        sb.append(", deleted=").append(deleted);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}