package com.tony.demo.message.dao;

import com.tony.demo.message.model.WechatMessageReplyStatus;
import com.tony.demo.message.model.WechatMessageReplyStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatMessageReplyStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    long countByExample(WechatMessageReplyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int deleteByExample(WechatMessageReplyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int insert(WechatMessageReplyStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int insertSelective(WechatMessageReplyStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    List<WechatMessageReplyStatus> selectByExample(WechatMessageReplyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    WechatMessageReplyStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WechatMessageReplyStatus record, @Param("example") WechatMessageReplyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WechatMessageReplyStatus record, @Param("example") WechatMessageReplyStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WechatMessageReplyStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message_reply_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WechatMessageReplyStatus record);
}