package com.tony.demo.example.mapper;

import com.tony.demo.example.bean.AuthorizerAppid;
import com.tony.demo.example.bean.AuthorizerAppidExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AuthorizerAppidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int countByExample(AuthorizerAppidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int deleteByExample(AuthorizerAppidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int insert(AuthorizerAppid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int insertSelective(AuthorizerAppid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    List<AuthorizerAppid> selectByExample(AuthorizerAppidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    AuthorizerAppid selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuthorizerAppid record, @Param("example") AuthorizerAppidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuthorizerAppid record, @Param("example") AuthorizerAppidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthorizerAppid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorizer_appid
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthorizerAppid record);
}